# Generated by Django 6.0.5 on 2026-05-22 22:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnchorSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-version'],
            },
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('canonical_name', models.CharField(max_length=200)),
                ('canvas_x', models.FloatField(default=0.0)),
                ('canvas_y', models.FloatField(default=0.0)),
                ('canvas_status', models.CharField(choices=[('unplaced', 'Unplaced'), ('auto', 'Auto-placed'), ('manual', 'Manually placed'), ('locked', 'Locked')], default='unplaced', max_length=20)),
                ('is_anchor', models.BooleanField(default=False)),
                ('genre_tags', models.JSONField(blank=True, default=list)),
                ('image_url', models.URLField(blank=True)),
                ('last_imported', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Festival',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug', models.SlugField(unique=True)),
                ('website', models.URLField(blank=True)),
                ('clashfinder_url', models.URLField(blank=True)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('location', models.CharField(max_length=200)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='ArtistEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField(default=1)),
                ('embedding_schema_version', models.CharField(blank=True, max_length=20)),
                ('anchor_set_hash', models.CharField(blank=True, max_length=64)),
                ('vector', models.JSONField()),
                ('source_summary', models.CharField(blank=True, max_length=100)),
                ('generated_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='core.artist')),
            ],
        ),
        migrations.CreateModel(
            name='CanvasMove',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_x', models.FloatField()),
                ('old_y', models.FloatField()),
                ('new_x', models.FloatField()),
                ('new_y', models.FloatField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('admin_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='canvas_moves', to='core.artist')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Cluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(default='#6366f1', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anchor_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leading_clusters', to='core.artist')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subclusters', to='core.cluster')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='LineupSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage', models.CharField(blank=True, max_length=100)),
                ('day', models.IntegerField(blank=True, null=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('slot_name', models.CharField(blank=True, max_length=200)),
                ('position', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('confirmed', 'Confirmed'), ('rumoured', 'Rumoured'), ('cancelled', 'Cancelled'), ('tbc', 'TBC')], default='confirmed', max_length=20)),
                ('raw_label', models.CharField(blank=True, max_length=200)),
                ('source_url', models.URLField(blank=True)),
                ('source_ref', models.CharField(blank=True, max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_slots', to='core.artist')),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineup_slots', to='core.festival')),
            ],
            options={
                'ordering': ['day', 'start_time', 'position'],
            },
        ),
        migrations.CreateModel(
            name='RawExternalData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('endpoint', models.CharField(max_length=100)),
                ('raw_data', models.JSONField()),
                ('fetched_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_data', to='core.artist')),
            ],
            options={
                'verbose_name_plural': 'raw external data',
                'ordering': ['-fetched_at'],
            },
        ),
        migrations.CreateModel(
            name='ScrapeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('importer_type', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('artists_found', models.IntegerField(default=0)),
                ('artists_new', models.IntegerField(default=0)),
                ('artists_updated', models.IntegerField(default=0)),
                ('errors', models.TextField(blank=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrape_logs', to='core.festival')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TasteSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('festival', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_sessions', to='core.festival')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('liked_artists', models.JSONField()),
                ('feedback', models.CharField(choices=[('good_shout', 'Good Shout'), ('not_for_me', 'Not for Me'), ('already_know', 'Already Know')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recommended_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rec_feedback', to='core.artist')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='core.tastesession')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnchorArtist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=100)),
                ('x_normalized', models.FloatField()),
                ('y_normalized', models.FloatField()),
                ('is_locked', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('anchor_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchors', to='core.anchorset')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anchor_assignments', to='core.artist')),
            ],
            options={
                'unique_together': {('anchor_set', 'artist')},
            },
        ),
        migrations.CreateModel(
            name='ArtistAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=200)),
                ('source', models.CharField(default='admin', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aliases', to='core.artist')),
            ],
            options={
                'unique_together': {('artist', 'alias')},
            },
        ),
        migrations.CreateModel(
            name='ArtistIdentifier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('external_id', models.CharField(max_length=200)),
                ('url', models.URLField(blank=True)),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identifiers', to='core.artist')),
            ],
            options={
                'unique_together': {('source', 'external_id')},
            },
        ),
        migrations.CreateModel(
            name='ArtistSignal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=20)),
                ('key', models.CharField(max_length=100)),
                ('value', models.FloatField()),
                ('confidence', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signals', to='core.artist')),
            ],
            options={
                'unique_together': {('artist', 'source', 'key')},
            },
        ),
        migrations.CreateModel(
            name='ArtistCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('strength', models.FloatField(default=1.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cluster_memberships', to='core.artist')),
                ('cluster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='core.cluster')),
            ],
            options={
                'unique_together': {('artist', 'cluster')},
            },
        ),
        migrations.CreateModel(
            name='SimilarityEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_score', models.FloatField(blank=True, null=True)),
                ('audio_score', models.FloatField(blank=True, null=True)),
                ('cooccurrence_score', models.FloatField(blank=True, null=True)),
                ('canvas_score', models.FloatField(blank=True, null=True)),
                ('cultural_affinity_score', models.FloatField(blank=True, null=True)),
                ('manual_score', models.FloatField(blank=True, null=True)),
                ('final_score', models.FloatField()),
                ('is_locked', models.BooleanField(default=False)),
                ('explanation', models.TextField(blank=True)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('weights_version', models.CharField(blank=True, max_length=50)),
                ('source_snapshot_id', models.CharField(blank=True, max_length=50)),
                ('computed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_a', to='core.artist')),
                ('artist_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sim_b', to='core.artist')),
            ],
            options={
                'ordering': ['-final_score'],
                'unique_together': {('artist_a', 'artist_b')},
            },
        ),
        migrations.CreateModel(
            name='TasteEdge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_lift', models.FloatField()),
                ('smoothed_lift', models.FloatField()),
                ('confidence', models.FloatField()),
                ('sample_size', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('festival', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='taste_edges', to='core.festival')),
                ('source_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_source_edges', to='core.artist')),
                ('target_artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_target_edges', to='core.artist')),
            ],
            options={
                'unique_together': {('source_artist', 'target_artist', 'festival')},
            },
        ),
        migrations.CreateModel(
            name='TasteSelection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='taste_selections', to='core.artist')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='selections', to='core.tastesession')),
            ],
            options={
                'unique_together': {('session', 'artist')},
            },
        ),
    ]
