# Generated by Django 6.0.5 on 2026-05-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='artist',
            name='marked_for_merge',
            field=models.BooleanField(default=False),
        ),
    ]
